#-------------------------------
# Site Settings
title: dp - [d]ata scientist in [p]harma
logo: '/images/logo.png'
description: Calipse is a modern magazine theme for Jekyll
color__scheme: dark # You can choose two modes: light and dark. By default, Calipse theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme).
cover__image: '/images/bg.jpg' # Add global cover image (this field adds a background to the top of the site.).


#-------------------------------
# Author Settings
author:
  author__name: Daniel Pham
  author__bio: I am a Melbourne-based data scientist with expertise in ML/AI, application development, data management and modelling in biopharma R&D and manufacturing. I am also a PhD candidate at The University of Melbourne with a research focus on robust data mining and optimisation.
social:
- {icon: "ion-logo-github", link: "https://github.com/danieltpham"}
#- {icon: "ion-send", link: "mailto:tiendungp@student.unimelb.edu.au"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/pham-daniel/"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/datanovella"}
- {icon: "ion-logo-googleplus", link: "https://orcid.org/0000-0002-2043-1495"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    # - title: 'About'
    #   url: '/about/'
    # - title: 'Contact'
    #   url: '/contact/'
    # - title: 'Pages'
    #   submenu:
    #   - url: '/elements/'
    #     title: 'Elements'


#-------------------------------
# Hero Settings
hero:
  hero__title: >
    Daniel Pham
  hero__description: I am a Melbourne-based data scientist with expertise in ML/AI, application development, data management and modelling in biopharma R&D and manufacturing. I am also a PhD candidate at The University of Melbourne with a research focus on robust data mining and optimisation.  Nice to meet you!


#-------------------------------
# Contact Settings
contact:
  email: dungphamtien99@gmail.com # Add your email for contact form

#-------------------------------
# Newsletter
# mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
# mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
# mailchimp__title: Newsletter
# mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
# mailchimp__button__text: Get news


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: # Add your GA Tracking Id